version: 2
machine:
  environment:
    PATH: "/opt/yarn/yarn-v1.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH}:${HOME}/${Ribbon}/node_modules/.bin"
    NODE_ENV: test
  node:
    version: 8.11.1
  npm:
    version: 6.0.0
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/ribbon
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo apt-get update && sudo apt-get upgrade -y
      - run: sudo apt-get install -y apt-transport-https
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - run: sudo apt-get update && sudo apt-get install -y yarn build-essential libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev
      - run: sudo npm install -g node-pre-gyp node-gyp
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
notify:
  webhooks:
    - url: https://skyhook.glitch.me/api/webhooks/431587377799233537/_kvV2bj5VcFeDX7gf5LmdwQIdVF_bA0xG_zYg-06-LPz8uZbiWLj2oH-1DX_vj1SsrSQ/circleci